name: Build-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 18 1 * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet-version: ["8.0.206"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install deps
        run: dotnet restore
      - name: Build solution
        run: dotnet build -c Release --no-restore
      - name: Test solution
        run: dotnet test -c Release --no-build
      - name: Create package
        run: dotnet pack -c Release --no-build
      - name: Archive build artifacts for OS-${{ matrix.os }}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: ./src/Ainoraz.EFCore.IncludeBuilder/bin/Release/
      - name: Benchmark
        run: dotnet run --project ./tests/Ainoraz.EFCore.IncludeBuilder.Benchmarks -c Release --no-build
      - name: Archive benchmarks for OS-${{ matrix.os }}
        uses: actions/upload-artifact@v4
        with:
          name: benchmarks-${{ matrix.os }}
          path: ./BenchmarkDotNet.Artifacts/
