name: Build-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: ["5.0.x"]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install deps
        run: dotnet restore
      - name: Build solution
        run: dotnet build -c Release --no-restore
      - name: Test solution
        run: dotnet test -c Release --no-build --no-restore
      - name: Create package
        run: dotnet pack -c Release --no-build --no-restore
      - name: Archive build artifacts for OS-${{ matrix.os }}
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-${{ matrix.os }}
          path: ./EFCore.IncludeBuilder/bin/Release/
      - name: Benchmark
        run: dotnet run --project ./EFCore.IncludeBuilder.Benchmarks -c Release --no-build --no-restore
      - name: Archive benchmarks for OS-${{ matrix.os }}
        uses: actions/upload-artifact@v2
        with:
          name: benchmarks-${{ matrix.os }}
          path: ./BenchmarkDotNet.Artifacts/